### ISSUE TITLE
EPIC: RW - Valet Parking Temporary 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-AMANDA-V7#23]
*In Progress*
_Epic_

**UAT Resource(s)**
- Mica

**Test Session Info:**
- [x] Scheduled
  - Date/Time: 01/04/2021 @ 3pm - 430pm
- [x] Updated Notes with UAT Results/Issues

**Comment by Nadin-Nader** [comment]
Performed the UAT  for the RW Valet Parking Temp folder with Micaela. She shared that the RW Valet Parking Temp folder is short and pretty straight forward. They also do **not**renew these. Below are the issues found by Micaela:

**Folder: 202017992300000**
**RSN: 12594223**

- When going over the info tab the Info "Event Start Date" is not editable
![Event Start Date uneditable.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/2683e1b7-6d52-4f27-ae8f-1015ca1b2d07)
- The Event Review Process needs to be taken out as they do not use it
- Event Review Process gives the ORA error  when "Accepted":

> ORA-06592: CASE not found while executing CASE sattement
> ORA-06512: at "AMANDA.COA_FOLDER_FEES", line 546
> ORA-06512: at "AMANDA.DEFAULTFEE_RW_50141", line 8
> ORA-06512: at "AMANDA.PROCESS_RW_00050560", line 192
> ORA-06512: at "AMANDA.DEFAULTPROCESS_RW_00050560", line 5
> ORA-06512: at 1

![Event Review ORA Error.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/be1a39ba-765d-455f-9144-654c2c4ad8e1)
- Not Adding Application fee ($35.00) after "Temporary Valet Intake" Process is "Accepted"
- ATD Tech Surcharge ROW Fee did not allow itself to be added via "Run Procedure". Had to manually add the fee and fee cost using "Insert"
- ATD Valet Temporary Application fee was not found in the "Run Procedure" menu. Only in The "Insert" menu

- **Seems like Micaela's permissions are correct for this folder**

## **Main Concerns in Order of Importance:**
- Not Adding Application fee ($35.00) after "Temporary Valet Intake" Process is "Accepted"
- The Event Review Process needs to be taken out as they do not use it
- When going over the info tab the Info "Event Start Date" is not editable
- ATD Valet Temporary Application fee was not found in the "Run Procedure" menu. Only in The "Insert" menu
- ATD Tech Surcharge ROW Fee did not allow itself to be added via "Run Procedure". Had to manually add the fee and fee cost using "Insert"
