### ISSUE TITLE
RW-TURP Seems as if the Franchise/COA Department info is set to PVT, it is not calculating and adding the Process info fees from the specific Tiers

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-AMANDA-V7#72]
RSN: 12591822
Fees are needed to be added when Franchise/COA Dept info is set to PVT only and during the "TURP Permit Intake" and the "Permit Extension" Process.

The Fees that need to be inserted are the TURP-Right Of Way Usage Fees (50315). This fee should only be inserted after the "TURP Permit Intake" Process is Accepted
The other fees are grouped into the TURP-Extension Right Of Way Usage Fees on V7under the "Insert" menu and these have multiple Info codes (50215, 50311-50321, 50356, 50357) depending on which Process info field is filled out and used on the process tab. It is not found in the "Run Procedure" menu. These fees should be inserted after the "Permit Extension" Process.

V6:
![TURP FEES V6.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/68c62151-d9d2-440f-b7d6-de39fc0c8749)
V7:
![TURP FEES V7.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/f76969d1-9e98-4483-b5e8-7d54f981fc7c)

**Comment by TracyLinder** [comment]
@Nadin-Nader can you please add details to this?
- Are fees supposed to be added when the info is not PVT?
- In this specific example, what fees & amount should have been inserted?

@TracyLinder 
- Are fees supposed to be added when the info is not PVT?
**Fees are needed to be added when Franchise/COA Dept info is set to PVT only**
- In this specific example, what fees & amount should have been inserted?
**It was not discussed as the fees would have varied between the extension and permitting. I also talked to Evelyn and she didnt know the exact pricing**

**Comment by Nadin-Nader** [comment]
Fees are needed to be added when Franchise/COA Dept info is set to PVT only and during the "TURP Permit Intake" and the "Permit Extension" Process.

The Fees that need to be inserted are the TURP-Right Of Way Usage Fees (50315). This fee should only be inserted after the "TURP Permit Intake" Process is Accepted
The other fees are grouped into the TURP-Extension Right Of Way Usage Fees on V7 and these have multiple Info codes (50215, 50311-50321, 50356, 50357) depending on which Process info field is filled out and used on the process tab. These fees should be inserted after the "Permit Extension" Process.

Below are the notes in detailed steps:

RSN: 12591822

- Tried to enter TURP Application fee via Run Procedure but it did not add
- Franchise/COA Department info was set to AEU (COA-Austin Energy) and COA Division was set to AEU (COA-Austin Energy) - Distribution
- Tried to change COA Division to PVT but it was not listed
- Changed Franchise/COA Department info to PVT and cleared out COA Division
- Went to Fee tab and was able to add the (50215) TURP Application Fee ($145)
- Added (50174) ATD Tech Surcharge ROW Fee ($5.80)
- Created the bill then went to the Process tab and added the Monility Bond Review ProcessWent to the Process info tab in the Mobility Bond Review Process
- Assigned it to Greg Pepper and set the To End Date as Jan 05, 2021 15:42:31
- Saved then entered the "Accepted" attempt to the Web Acceptance Process
- Went to main Info tab and set "Yes" to "Activate Upon Payment" field
(Franchise/COA Department was still set to PVT)
- Cancelled fees
- Entered "Approved" attempt to the "Event Review" Process, it didnt error out and it added the (50336) Aterial/Collector Street Security fee  $2000 but they dont want the process at all
- Went to "TURP Permit Intake" Process and "Accepted" it
- Approved "TURP Review" Process
- Was able to issue permit with Violation warning bypassed
- Then went to "Permit Extension" Process (it was added after permit issuance)
- Went to the process info in the process and set the "Extension Start Date" to Dec 30, 2020, "Extension End Date" was left blank, "Number of Days for Extension" set to 180, "# Days in Tier 1" to 180, "# Days in Tier 2" to 0, "# Days in Tier 3" to 0, "# Days in Tier 4" to 0
- Saved and it entered an "Extension End Date" to Jun 27, 2021
- Entered Attempt of "Extension Granted"
- Went to folder tab and the "Expires" Date was Feb 26, 2021
- Then went back to "Permit Extension" Process
- Went to the process info in the process and set the "Extension Start Date" to Feb 27, 2021, "Extension End Date" was left blank, "Number of Days for Extension" set to 180, "# Days in Tier 1" to 180, "# Days in Tier 2" to 0, "# Days in Tier 3" to 0, "# Days in Tier 4" to 0
- Saved and it entered an "Extension End Date" to Aug 25, 2021
- Entered Attempt of "Extension Granted"
- Went to folder tab and the "Expires" Date was still Feb 26, 2021
- It also did not add the fees
- Went to Info tab and changed the Franchise/COA Department from PVT to AEU COA-Austin Energy
- Once Again went back to "Permit Extension" Process
- Went to the process info in the process and set the "Extension Start Date" to Feb 27, 2021, "Extension End Date" was left blank, "Number of Days for Extension" set to 10, "# Days in Tier 1" to 10, "# Days in Tier 2" to 0, "# Days in Tier 3" to 0, "# Days in Tier 4" to 0
- Saved and it entered an "Extension End Date" to Mar 08, 2021
- Entered Attempt of "Extension Granted"
- Went to folder tab and the "Expires" Date changed to Mar 08, 2021 but didnt add the fees.

**Comment by TracyLinder** [comment]
I just tested PVT fees on V6 and the fees did not insert after I approved the TURP Permitting Review process. So this part seems like a V6 bug.

**Comment by TracyLinder** [comment]
I did extensive testing on this, and compared to V6. All fees on PVT are inserting as they do in V6. See test RSN 12594885.
