### ISSUE TITLE
Temp Valet: Event Start Date Info not editable

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-AMANDA-V7#76]
RSN: 12594223

**What is happening:**
User goes to the Info tab and under the Event Start/End 3 section; the Event Start and Event Date fields are un-editable. User cannot edit via the main blue Edit button and the single row edit.

**What's Supposed to happen:**
User goes to the Info tab and is able to edit the Event Start and Event End dates under the Event Start/End section using the blue edit button or the single row edit feature.

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/85fadf47-d048-4246-baf3-80e5bfed144e)

**Comment by Nadin-Nader** [comment]
RSN: 12594223

What is happening:
User goes to the Info tab and under the Event Start/End 3 section; the Event Start and Event Date fields are un-editable. User cannot edit via the main blue Edit button and the single row edit.

What's Supposed to happen:
User goes to the Info tab and is able to edit the Event Start and Event End dates under the Event Start/End section using the blue edit button or the single row edit feature.

**Comment by TracyLinder** [comment]
I have another ticket open for this, #93. Closing this one.
