### ISSUE TITLE
EX: Folder conditions missing

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-AMANDA-V7#80]

**Comment by TracyLinder** [comment]
@Nadin-Nader I'm able to see the folder conditions on EX. Can you check with Izzy to see if this has been corrected for her? If not we'll need to check her permissions. Thank you.

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/0540e2a9-49a2-4f29-b0ce-1fc5fe5ab6a1)

**Comment by Nadin-Nader** [comment]
@TracyLinder I reached out to Izzy via Teams Chat and asked her to check. I will follow up with her later today to see if she was able to test. If not, I will test it with her when she responds to the chat :)

**Status:**
Waiting for Izzy to respond/let me know the outcome

**Comment by Nadin-Nader** [comment]
@TracyLinder  so Per George's comment on Trello :

> George Shirai 2 hours ago
> @nadinnader1 @tracylinder I compared the RW folder infos between V6 TEST, V6 PROD, and V7 TEST and they match up. This purpose of this UAT is to make sure the V7 system is operating the same way as the V6 system. If the user is looking for folder infos that existed in the past, that's something we can address after V7 go-live.

Should we put this in the IceBox?

**Comment by TracyLinder** [comment]
@Nadin-Nader I don't think so. Whoever did the UAT on this with you must be working off of old memory; these infos were removed on purpose and we don't have a request to add them back. Let's just close this one out.
