### ISSUE TITLE
Vendor: Cannot edit "Event Start Date" Info

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-AMANDA-V7#83]
**What is happening:**
User goes to the Info tab and under the Event Start/End section; the Event Start field is un-editable. User cannot edit via the main blue Edit button and the single row edit.

**What's Supposed to happen:**
User goes to the Info tab and is able to edit the Event Start and Event End dates under the Event Start/End section using the blue edit button or the single row edit feature.

![Cannot edit Event start date in info.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/aeb56416-1440-4513-b38a-bb60e5e3f4bb)

**Comment by Nadin-Nader** [comment]
![Cannot edit Event start date in info.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/28019019-f711-4036-ab1a-fbeb3c67f944)

**Comment by TracyLinder** [comment]
This error is being tracked on a different issue. Closing.
